name: Build & Push Docker Image
on:
  push:
    branches:
      - main
env:
  MINOR_VERSION: 3
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Run tests
        run: ./gradlew test
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Build
        run: ./gradlew clean build -x test

      - name: Log in NCP Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.NCP_ACCESS_KEY }}
          password: ${{ secrets.NCP_SECRET_KEY }}

      - name: Declare some variables
        id: git-commit-sha
        run: echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_OUTPUT

      # build push action
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.CONTAINER_REGISTRY_URL }}/malan-alerter-be:0.${{ env.MINOR_VERSION }}.${{ steps.git-commit-sha.outputs.SHA_SHORT }}
#            ${{ secrets.CONTAINER_REGISTRY_URL }}/malan-alerter-be:latest
          platforms: linux/amd64
#          cache-from: type=registry,ref=${{ secrets.CONTAINER_REGISTRY_URL }}/malan-alerter-be:latest
#          cache-to: type=inline
  deploy:
    needs:
    - build-and-push-image
    - test
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote script
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.REMOTE_HOST }}
          port: 20022
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/hc07car/malan-alerter
            sh patch-be.sh 0.${{ env.MINOR_VERSION }}.${{ steps.git-commit-sha.outputs.SHA_SHORT  }}